on:
  push:
    branches:
      - master
      - fix_image_panic
  pull_request:

jobs:
  test-stable:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
    name: cargo test
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          profile: minimal
          override: true

      # Test packages in deeper-to-higher dependency order
      - name: cargo test piet
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=piet/Cargo.toml --all-features

      - name: cargo test piet-cairo
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=piet-cairo/Cargo.toml --all-features
        if: contains(matrix.os, 'ubuntu')

      - name: cargo test piet-coregraphics
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=piet-coregraphics/Cargo.toml --all-features
        if: contains(matrix.os, 'macOS')

      - name: cargo test piet-direct2d
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=piet-direct2d/Cargo.toml --all-features
        if: contains(matrix.os, 'windows')

      - name: cargo test piet-svg
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=piet-svg/Cargo.toml --all-features

      - name: cargo test piet-common
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=piet-common/Cargo.toml --features=png

